# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import workerServer.workerServer_pb2 as workerServer__pb2


class WorkerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.migrate = channel.unary_unary(
                '/Worker/migrate',
                request_serializer=workerServer__pb2.MigrationInput.SerializeToString,
                response_deserializer=workerServer__pb2.MigrationOutput.FromString,
                )
        self.storeDate = channel.unary_unary(
                '/Worker/storeDate',
                request_serializer=workerServer__pb2.StoreDataInput.SerializeToString,
                response_deserializer=workerServer__pb2.StoreDataOutput.FromString,
                )


class WorkerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def migrate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def storeDate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'migrate': grpc.unary_unary_rpc_method_handler(
                    servicer.migrate,
                    request_deserializer=workerServer__pb2.MigrationInput.FromString,
                    response_serializer=workerServer__pb2.MigrationOutput.SerializeToString,
            ),
            'storeDate': grpc.unary_unary_rpc_method_handler(
                    servicer.storeDate,
                    request_deserializer=workerServer__pb2.StoreDataInput.FromString,
                    response_serializer=workerServer__pb2.StoreDataOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Worker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Worker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def migrate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Worker/migrate',
            workerServer__pb2.MigrationInput.SerializeToString,
            workerServer__pb2.MigrationOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def storeDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Worker/storeDate',
            workerServer__pb2.StoreDataInput.SerializeToString,
            workerServer__pb2.StoreDataOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
